//
//  Config.h
//  ios-sinch-messaging-tutorial
//

#define SINCH_APPLICATION_KEY @""

#define SINCH_APPLICATION_SECRET @""

#define SINCH_ENVIRONMENT_HOST @""

#define PARSE_APPLICATION_ID @""

#define PARSE_CLIENT_KEY @""

#define SINCH_MESSAGE_RECIEVED @"SINCH_MESSAGE_RECIEVED"
#define SINCH_MESSAGE_SENT @"SINCH_MESSAGE_SENT"
#define SINCH_MESSAGE_DELIVERED @"SINCH_MESSAGE_DELIVERED"
#define SINCH_MESSAGE_FAILED @"SINCH_MESSAGE_DELIVERED"