//
//  Config.h
//  ios-sinch-messaging-tutorial
//

#define SINCH_APPLICATION_KEY @"adc6214c-807c-4d50-80b5-e647ce70c451"

#define SINCH_APPLICATION_SECRET @"qKpa2pOUDkWs31Z3c7xUIQ=="

#define SINCH_ENVIRONMENT_HOST @"sandbox.sinch.com"

#define PARSE_APPLICATION_ID @"Xa7NYG9djHmn6Imyxu3KyYrn2YKAj86Q5pXyobLG"

#define PARSE_CLIENT_KEY @"Hig6kF0OHHQkUJmyn1gIqiT5PtKuKUUxYxR9JFfG"

#define SINCH_MESSAGE_RECIEVED @"SINCH_MESSAGE_RECIEVED"
#define SINCH_MESSAGE_SENT @"SINCH_MESSAGE_SENT"
#define SINCH_MESSAGE_DELIVERED @"SINCH_MESSAGE_DELIVERED"
#define SINCH_MESSAGE_FAILED @"SINCH_MESSAGE_DELIVERED"